# Generated by Django 4.1.13 on 2025-08-26 09:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_post_interactions'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={},
        ),
    ]
