CATEGORY_MAPPINGS = {
    "pizza": "food",
    "hamburger": "food", 
    "cheeseburger": "food",
    "hot dog": "food",
    "sandwich": "food",
    "taco": "food",
    "burrito": "food",
    "coffee": "food",
    "espresso": "food",
    "tea": "food",
    "beer": "food",
    "wine": "food",
    "cocktail": "food",
    "ice cream": "food",
    "cake": "food",
    "donut": "food",
    "cookie": "food",
    "bread": "food",
    "bagel": "food",
    "pretzel": "food",
    "hot pot": "food",
    "soup": "food",
    "salad": "food",
    "fruit": "food",
    "apple": "food",
    "banana": "food",
    "orange": "food",
    "strawberry": "food",
    "dish": "food",
    "plate": "food",
    "bowl": "food",
    

    "car": "vehicles",
    "sports car": "vehicles",
    "convertible": "vehicles",
    "limousine": "vehicles",
    "pickup truck": "vehicles",
    "garbage truck": "vehicles",
    "fire truck": "vehicles",
    "ambulance": "vehicles",
    "bus": "vehicles",
    "minibus": "vehicles",
    "trolleybus": "vehicles",
    "motorcycle": "vehicles",
    "motor scooter": "vehicles",
    "bicycle": "vehicles",
    "tricycle": "vehicles",
    "van": "vehicles",
    "truck": "vehicles",
    "taxi": "vehicles",
    "police car": "vehicles",
    "jeep": "vehicles",
    

    "dog": "animals",
    "cat": "animals",
    "egyptian cat": "animals",
    "tiger": "animals",
    "lion": "animals",
    "elephant": "animals",
    "horse": "animals",
    "cow": "animals",
    "pig": "animals",
    "sheep": "animals",
    "bird": "animals",
    "peacock": "animals",
    "eagle": "animals",
    "owl": "animals",
    "bear": "animals",
    "wolf": "animals",
    "fox": "animals",
    "rabbit": "animals",
    "deer": "animals",
    "monkey": "animals",
    "zebra": "animals",
    "giraffe": "animals",
    "wallaby": "animals",
    "kangaroo": "animals",
    

    "football": "sports",
    "basketball": "sports",
    "tennis": "sports",
    "baseball": "sports",
    "soccer": "sports",
    "golf": "sports",
    "swimming": "sports",
    "running": "sports",
    "cycling": "sports",
    "football helmet": "sports",
    "basketball hoop": "sports",
    "tennis racket": "sports",
    "baseball bat": "sports",
    "golf ball": "sports",
    "croquet ball": "sports",
    "racket": "sports",
    "helmet": "sports",
    
 
    "laptop": "technology",
    "computer": "technology",
    "notebook": "technology",
    "tablet": "technology",
    "phone": "technology",
    "camera": "technology",
    "screen": "technology",
    "monitor": "technology",
    "keyboard": "technology",
    "mouse": "technology",
    "joystick": "technology",
    "headphones": "technology",
    "speaker": "technology",
    "television": "technology",
    "remote": "technology",
    

    "shirt": "clothing",
    "dress": "clothing",
    "pants": "clothing",
    "shoes": "clothing",
    "hat": "clothing",
    "jacket": "clothing",
    "sweater": "clothing",
    "coat": "clothing",
    "tie": "clothing",
    "sock": "clothing",
    "glove": "clothing",
    "belt": "clothing",
    "bag": "clothing",
    "purse": "clothing",
    "backpack": "clothing",
    

    "chair": "furniture",
    "table": "furniture",
    "bed": "furniture",
    "sofa": "furniture",
    "couch": "furniture",
    "desk": "furniture",
    "lamp": "furniture",
    "mirror": "furniture",
    "clock": "furniture",
    "vase": "furniture",
    "pillow": "furniture",
    "blanket": "furniture",
    

    "flower": "nature",
    "tree": "nature",
    "plant": "nature",
    "leaf": "nature",
    "grass": "nature",
    "mountain": "nature",
    "beach": "nature",
    "ocean": "nature",
    "lake": "nature",
    "river": "nature",
    "sky": "nature",
    "cloud": "nature",
    "sunset": "nature",
    "sunrise": "nature"
}